services:
  web:
    container_name: ui
    build:
      context: ../../packages/web
      dockerfile: Dockerfile
    ports:
      - "5173:5173"
    volumes:
     - .:/app
     - node_modules:/app/node_modules
    env_file:
      - .env
    stdin_open: true
    tty: true
    command: npm run dev -- --host

volumes:
  node_modules: